#!/usr/bin/env bash

sudo apt update -qy
sudo apt install software-properties-common apt-transport-https -qy

sudo mkdir -p /etc/apt/keyrings

curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null

sudo add-apt-repository "deb https://packages.microsoft.com/repos/vscode stable main"

sudo apt update -qy && sudo apt upgrade -qy

sudo apt install code -qy