#!/usr/bin/env bash

echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections

sudo apt update -qy

sudo apt-get install wget gpg -qy

wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
rm -f packages.microsoft.gpg

sudo apt install apt-transport-https -qy
sudo apt update -qy
sudo apt install code -qy

sudo apt autoremove -qy